services:
  # Web service (free tier compatible)
  # Use this for Render's free tier
  - type: web
    name: discord-bot-web
    env: node
    buildCommand: npm install && chmod +x web-startup.sh
    startCommand: ./web-startup.sh
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_NO_WARNINGS
        value: 1
      - key: DISCORD_TOKEN
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: ROBLOX_COOKIE
        sync: false
      - key: ROBLOX_GROUP_ID
        sync: false
      - key: DATABASE_URL
        sync: false
        
  # Background worker service (requires paid plan)
  # Only use this if you have a paid Render plan
  - type: worker
    name: discord-bot-worker
    env: node
    buildCommand: npm install && chmod +x startup.sh
    startCommand: ./startup.sh
    plan: free
    envVars:
      - key: RENDER_SERVICE_TYPE
        value: worker
      - key: NODE_NO_WARNINGS
        value: 1
      - key: NO_PORT_SCAN
        value: true
      - key: DISCORD_TOKEN
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: ROBLOX_COOKIE
        sync: false
      - key: ROBLOX_GROUP_ID
        sync: false
      - key: DATABASE_URL
        sync: false