# Render.yaml configuration file

services:
  # Main Discord Bot Service - Uses Web Service for Free Tier
  - type: web
    name: discord-bot
    env: node
    # Build command for Render
    buildCommand: npm install && chmod +x web-startup.sh
    # Start command - using our web-service wrapper
    startCommand: ./web-startup.sh
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 5000
      - key: DISCORD_TOKEN
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: ROBLOX_COOKIE
        sync: false
      - key: ROBLOX_GROUP_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: discord-bot-db
          property: connectionString
    # Health check endpoint
    healthCheckPath: /health
    # Free tier settings
    plan: free
    # Auto-deploy settings
    autoDeploy: false

databases:
  - name: discord-bot-db
    plan: free
    databaseName: discordbot
    ipAllowList: []